added strict mode to setup script

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,4 +1,7 @@
 #!/bin/bash
+set -uo pipefail
+trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
+IFS=$'\n\t'
 
 echo "Hello. This is setup."
 
